# Generated by Django 5.1.5 on 2025-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocArticle',
            fields=[
                ('n_enregistrement', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('titre_article', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.CharField(default='0', max_length=30)),
                ('domaine', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=100)),
                ('periodicite', models.CharField(default='0', max_length=3)),
                ('vol', models.CharField(max_length=25)),
                ('tom', models.CharField(max_length=25)),
                ('num', models.CharField(max_length=25)),
                ('statut', models.CharField(default='0', max_length=10)),
                ('n_periodique', models.SmallIntegerField(blank=True, null=True)),
                ('lang', models.CharField(max_length=2)),
                ('type_support', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'doc_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocCollecte',
            fields=[
                ('n_enregistrement', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titre_document', models.CharField(max_length=200)),
                ('source_document', models.CharField(max_length=100)),
                ('support_document', models.CharField(max_length=50)),
                ('date_collecte', models.DateField()),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'doc_collecte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocMonographie',
            fields=[
                ('n_enregistrement', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('pages', models.CharField(default='0', max_length=30)),
                ('domaine', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=100)),
                ('statut', models.CharField(default='0', max_length=10)),
                ('n_periodique', models.SmallIntegerField(blank=True, null=True)),
                ('lang', models.CharField(max_length=2)),
                ('type_support', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'doc_monographie',
                'managed': False,
            },
        ),
    ]
